version: '3.1'
services:
  backend:
    container_name: docker-node-backend
    restart: always
    build: 
      context: ./backend/
    ports: 
      - '8883:8883'
    links:
      - mongo
  frontend:
    container_name: docker-node-frontend
    restart: always
    build: 
      context: ./frontend/
    ports: 
      - '8080:8080'
    links:
      - backend
  mongo:
    container_name: mongo
    image: mongo
    ports: 
      - '27017:27017'